import { Country } from '@/shared/types';

export const COUNTRIES_DATA: Country[] = [
	{
		name: 'Srbija',
		callingNumber: '+381',
		flag: 'https://flagsapi.com/RS/flat/64.png',
		code: 'RS',
	},
	{
		name: 'Bosna i Hercegovina',
		callingNumber: '+387',
		flag: 'https://flagsapi.com/BA/flat/64.png',
		code: 'BA',
	},
	{
		name: 'Afganistan',
		callingNumber: '+93',
		code: 'AF',
		flag: 'https://flagsapi.com/AF/flat/64.png',
	},
	{
		name: 'Albanija',
		callingNumber: '+355',
		code: 'AL',
		flag: 'https://flagsapi.com/AL/flat/64.png',
	},
	{
		name: 'Alžir',
		callingNumber: '+213',
		code: 'DZ',
		flag: 'https://flagsapi.com/DZ/flat/64.png',
	},
	{
		name: 'Andora',
		callingNumber: '+376',
		code: 'AD',
		flag: 'https://flagsapi.com/AD/flat/64.png',
	},
	{
		name: 'Angola',
		callingNumber: '+244',
		code: 'AO',
		flag: 'https://flagsapi.com/AO/flat/64.png',
	},
	{
		name: 'Antigva i Barbuda',
		callingNumber: '+1268',
		code: 'AG',
		flag: 'https://flagsapi.com/AG/flat/64.png',
	},
	{
		name: 'Argentina',
		callingNumber: '+54',
		code: 'AR',
		flag: 'https://flagsapi.com/AR/flat/64.png',
	},
	{
		name: 'Jermenija',
		callingNumber: '+374',
		code: 'AM',
		flag: 'https://flagsapi.com/AM/flat/64.png',
	},
	{
		name: 'Australija',
		callingNumber: '+61',
		code: 'AU',
		flag: 'https://flagsapi.com/AU/flat/64.png',
	},
	{
		name: 'Austrija',
		callingNumber: '+43',
		code: 'AT',
		flag: 'https://flagsapi.com/AT/flat/64.png',
	},
	{
		name: 'Azerbejdžan',
		callingNumber: '+994',
		code: 'AZ',
		flag: 'https://flagsapi.com/AZ/flat/64.png',
	},
	{
		name: 'Bahami',
		callingNumber: '+1242',
		code: 'BS',
		flag: 'https://flagsapi.com/BS/flat/64.png',
	},
	{
		name: 'Bahrein',
		callingNumber: '+973',
		code: 'BH',
		flag: 'https://flagsapi.com/BH/flat/64.png',
	},
	{
		name: 'Bangladeš',
		callingNumber: '+880',
		code: 'BD',
		flag: 'https://flagsapi.com/BD/flat/64.png',
	},
	{
		name: 'Barbados',
		callingNumber: '+1246',
		code: 'BB',
		flag: 'https://flagsapi.com/BB/flat/64.png',
	},
	{
		name: 'Belorusija',
		callingNumber: '+375',
		code: 'BY',
		flag: 'https://flagsapi.com/BY/flat/64.png',
	},
	{
		name: 'Belgija',
		callingNumber: '+32',
		code: 'BE',
		flag: 'https://flagsapi.com/BE/flat/64.png',
	},
	{
		name: 'Beliz',
		callingNumber: '+501',
		code: 'BZ',
		flag: 'https://flagsapi.com/BZ/flat/64.png',
	},
	{
		name: 'Benin',
		callingNumber: '+229',
		code: 'BJ',
		flag: 'https://flagsapi.com/BJ/flat/64.png',
	},
	{
		name: 'Butan',
		callingNumber: '+975',
		code: 'BT',
		flag: 'https://flagsapi.com/BT/flat/64.png',
	},
	{
		name: 'Bocvana',
		callingNumber: '+267',
		code: 'BW',
		flag: 'https://flagsapi.com/BW/flat/64.png',
	},
	{
		name: 'Brazil',
		callingNumber: '+55',
		code: 'BR',
		flag: 'https://flagsapi.com/BR/flat/64.png',
	},
	{
		name: 'Brunej',
		callingNumber: '+673',
		code: 'BN',
		flag: 'https://flagsapi.com/BN/flat/64.png',
	},
	{
		name: 'Bugarska',
		callingNumber: '+359',
		code: 'BG',
		flag: 'https://flagsapi.com/BG/flat/64.png',
	},
	{
		name: 'Burkina Faso',
		callingNumber: '+226',
		code: 'BF',
		flag: 'https://flagsapi.com/BF/flat/64.png',
	},
	{
		name: 'Burundi',
		callingNumber: '+257',
		code: 'BI',
		flag: 'https://flagsapi.com/BI/flat/64.png',
	},
	{
		name: 'Kambodža',
		callingNumber: '+855',
		code: 'KH',
		flag: 'https://flagsapi.com/KH/flat/64.png',
	},
	{
		name: 'Kamerun',
		callingNumber: '+237',
		code: 'CM',
		flag: 'https://flagsapi.com/CM/flat/64.png',
	},
	{
		name: 'Kanada',
		callingNumber: '+1',
		code: 'CA',
		flag: 'https://flagsapi.com/CA/flat/64.png',
	},
	{
		name: 'Centralnoafrička Republika',
		callingNumber: '+236',
		code: 'CF',
		flag: 'https://flagsapi.com/CF/flat/64.png',
	},
	{
		name: 'Čad',
		callingNumber: '+235',
		code: 'TD',
		flag: 'https://flagsapi.com/TD/flat/64.png',
	},
	{
		name: 'Češka',
		callingNumber: '+420',
		code: 'CZ',
		flag: 'https://flagsapi.com/CZ/flat/64.png',
	},
	{
		name: 'Čile',
		callingNumber: '+56',
		code: 'CL',
		flag: 'https://flagsapi.com/CL/flat/64.png',
	},
	{
		name: 'Kina',
		callingNumber: '+86',
		code: 'CN',
		flag: 'https://flagsapi.com/CN/flat/64.png',
	},
	{
		name: 'Kolumbija',
		callingNumber: '+57',
		code: 'CO',
		flag: 'https://flagsapi.com/CO/flat/64.png',
	},
	{
		name: 'Komori',
		callingNumber: '+269',
		code: 'KM',
		flag: 'https://flagsapi.com/KM/flat/64.png',
	},
	{
		name: 'Kongo (Brazavil)',
		callingNumber: '+242',
		code: 'CG',
		flag: 'https://flagsapi.com/CG/flat/64.png',
	},
	{
		name: 'Kongo (Kinsasa)',
		callingNumber: '+243',
		code: 'CD',
		flag: 'https://flagsapi.com/CD/flat/64.png',
	},
	{
		name: 'Kostarika',
		callingNumber: '+506',
		code: 'CR',
		flag: 'https://flagsapi.com/CR/flat/64.png',
	},
	{
		name: "Kot d'Ivoar",
		callingNumber: '+225',
		code: 'CI',
		flag: 'https://flagsapi.com/CI/flat/64.png',
	},
	{
		name: 'Hrvatska',
		callingNumber: '+385',
		code: 'HR',
		flag: 'https://flagsapi.com/HR/flat/64.png',
	},
	{
		name: 'Kuba',
		callingNumber: '+53',
		code: 'CU',
		flag: 'https://flagsapi.com/CU/flat/64.png',
	},
	{
		name: 'Kipar',
		callingNumber: '+357',
		code: 'CY',
		flag: 'https://flagsapi.com/CY/flat/64.png',
	},
	{
		name: 'Češka',
		callingNumber: '+420',
		code: 'CZ',
		flag: 'https://flagsapi.com/CZ/flat/64.png',
	},
	{
		name: 'Danska',
		callingNumber: '+45',
		code: 'DK',
		flag: 'https://flagsapi.com/DK/flat/64.png',
	},
	{
		name: 'Džibuti',
		callingNumber: '+253',
		code: 'DJ',
		flag: 'https://flagsapi.com/DJ/flat/64.png',
	},
	{
		name: 'Dominika',
		callingNumber: '+1767',
		code: 'DM',
		flag: 'https://flagsapi.com/DM/flat/64.png',
	},
	{
		name: 'Dominikanska Republika',
		callingNumber: '+1809',
		code: 'DO',
		flag: 'https://flagsapi.com/DO/flat/64.png',
	},
	{
		name: 'Ekvador',
		callingNumber: '+593',
		code: 'EC',
		flag: 'https://flagsapi.com/EC/flat/64.png',
	},
	{
		name: 'Egipat',
		callingNumber: '+20',
		code: 'EG',
		flag: 'https://flagsapi.com/EG/flat/64.png',
	},
	{
		name: 'Salvador',
		callingNumber: '+503',
		code: 'SV',
		flag: 'https://flagsapi.com/SV/flat/64.png',
	},
	{
		name: 'Ekvatorska Gvineja',
		callingNumber: '+240',
		code: 'GQ',
		flag: 'https://flagsapi.com/GQ/flat/64.png',
	},
	{
		name: 'Eritreja',
		callingNumber: '+291',
		code: 'ER',
		flag: 'https://flagsapi.com/ER/flat/64.png',
	},
	{
		name: 'Estonija',
		callingNumber: '+372',
		code: 'EE',
		flag: 'https://flagsapi.com/EE/flat/64.png',
	},
	{
		name: 'Esvatini',
		callingNumber: '+268',
		code: 'SZ',
		flag: 'https://flagsapi.com/SZ/flat/64.png',
	},
	{
		name: 'Esvatini',
		callingNumber: '+268',
		code: 'SZ',
		flag: 'https://flagsapi.com/SZ/flat/64.png',
	},
	{
		name: 'Etiopija',
		callingNumber: '+251',
		code: 'ET',
		flag: 'https://flagsapi.com/ET/flat/64.png',
	},
	{
		name: 'Fidži',
		callingNumber: '+679',
		code: 'FJ',
		flag: 'https://flagsapi.com/FJ/flat/64.png',
	},
	{
		name: 'Finska',
		callingNumber: '+358',
		code: 'FI',
		flag: 'https://flagsapi.com/FI/flat/64.png',
	},
	{
		name: 'Francuska',
		callingNumber: '+33',
		code: 'FR',
		flag: 'https://flagsapi.com/FR/flat/64.png',
	},
	{
		name: 'Gabon',
		callingNumber: '+241',
		code: 'GA',
		flag: 'https://flagsapi.com/GA/flat/64.png',
	},
	{
		name: 'Gambia',
		callingNumber: '+220',
		code: 'GM',
		flag: 'https://flagsapi.com/GM/flat/64.png',
	},
	{
		name: 'Gruzija',
		callingNumber: '+995',
		code: 'GE',
		flag: 'https://flagsapi.com/GE/flat/64.png',
	},
	{
		name: 'Nemačka',
		callingNumber: '+49',
		code: 'DE',
		flag: 'https://flagsapi.com/DE/flat/64.png',
	},
	{
		name: 'Gana',
		callingNumber: '+233',
		code: 'GH',
		flag: 'https://flagsapi.com/GH/flat/64.png',
	},
	{
		name: 'Grčka',
		callingNumber: '+30',
		code: 'GR',
		flag: 'https://flagsapi.com/GR/flat/64.png',
	},
	{
		name: 'Grenada',
		callingNumber: '+1473',
		code: 'GD',
		flag: 'https://flagsapi.com/GD/flat/64.png',
	},
	{
		name: 'Gvajana',
		callingNumber: '+592',
		code: 'GY',
		flag: 'https://flagsapi.com/GY/flat/64.png',
	},
	{
		name: 'Haiti',
		callingNumber: '+509',
		code: 'HT',
		flag: 'https://flagsapi.com/HT/flat/64.png',
	},
	{
		name: 'Honduras',
		callingNumber: '+504',
		code: 'HN',
		flag: 'https://flagsapi.com/HN/flat/64.png',
	},
	{
		name: 'Mađarska',
		callingNumber: '+36',
		code: 'HU',
		flag: 'https://flagsapi.com/HU/flat/64.png',
	},
	{
		name: 'Island',
		callingNumber: '+354',
		code: 'IS',
		flag: 'https://flagsapi.com/IS/flat/64.png',
	},
	{
		name: 'Indija',
		callingNumber: '+91',
		code: 'IN',
		flag: 'https://flagsapi.com/IN/flat/64.png',
	},
	{
		name: 'Indonezija',
		callingNumber: '+62',
		code: 'ID',
		flag: 'https://flagsapi.com/ID/flat/64.png',
	},
	{
		name: 'Iran',
		callingNumber: '+98',
		code: 'IR',
		flag: 'https://flagsapi.com/IR/flat/64.png',
	},
	{
		name: 'Irak',
		callingNumber: '+964',
		code: 'IQ',
		flag: 'https://flagsapi.com/IQ/flat/64.png',
	},
	{
		name: 'Irska',
		callingNumber: '+353',
		code: 'IE',
		flag: 'https://flagsapi.com/IE/flat/64.png',
	},
	{
		name: 'Izrael',
		callingNumber: '+972',
		code: 'IL',
		flag: 'https://flagsapi.com/IL/flat/64.png',
	},
	{
		name: 'Italija',
		callingNumber: '+39',
		code: 'IT',
		flag: 'https://flagsapi.com/IT/flat/64.png',
	},
	{
		name: 'Jamajka',
		callingNumber: '+1876',
		code: 'JM',
		flag: 'https://flagsapi.com/JM/flat/64.png',
	},
	{
		name: 'Japan',
		callingNumber: '+81',
		code: 'JP',
		flag: 'https://flagsapi.com/JP/flat/64.png',
	},
	{
		name: 'Jordan',
		callingNumber: '+962',
		code: 'JO',
		flag: 'https://flagsapi.com/JO/flat/64.png',
	},
	{
		name: 'Kazahstan',
		callingNumber: '+7',
		code: 'KZ',
		flag: 'https://flagsapi.com/KZ/flat/64.png',
	},
	{
		name: 'Kenija',
		callingNumber: '+254',
		code: 'KE',
		flag: 'https://flagsapi.com/KE/flat/64.png',
	},
	{
		name: 'Kiribati',
		callingNumber: '+686',
		code: 'KI',
		flag: 'https://flagsapi.com/KI/flat/64.png',
	},
	{
		name: 'Kuvajt',
		callingNumber: '+965',
		code: 'KW',
		flag: 'https://flagsapi.com/KW/flat/64.png',
	},
	{
		name: 'Kirgistan',
		callingNumber: '+996',
		code: 'KG',
		flag: 'https://flagsapi.com/KG/flat/64.png',
	},
	{
		name: 'Laos',
		callingNumber: '+856',
		code: 'LA',
		flag: 'https://flagsapi.com/LA/flat/64.png',
	},
	{
		name: 'Letonija',
		callingNumber: '+371',
		code: 'LV',
		flag: 'https://flagsapi.com/LV/flat/64.png',
	},
	{
		name: 'Liban',
		callingNumber: '+961',
		code: 'LB',
		flag: 'https://flagsapi.com/LB/flat/64.png',
	},
	{
		name: 'Lesoto',
		callingNumber: '+266',
		code: 'LS',
		flag: 'https://flagsapi.com/LS/flat/64.png',
	},
	{
		name: 'Liberija',
		callingNumber: '+231',
		code: 'LR',
		flag: 'https://flagsapi.com/LR/flat/64.png',
	},
	{
		name: 'Libija',
		callingNumber: '+218',
		code: 'LY',
		flag: 'https://flagsapi.com/LY/flat/64.png',
	},
	{
		name: 'Lihtenštajn',
		callingNumber: '+423',
		code: 'LI',
		flag: 'https://flagsapi.com/LI/flat/64.png',
	},
	{
		name: 'Litvanija',
		callingNumber: '+370',
		code: 'LT',
		flag: 'https://flagsapi.com/LT/flat/64.png',
	},
	{
		name: 'Luksemburg',
		callingNumber: '+352',
		code: 'LU',
		flag: 'https://flagsapi.com/LU/flat/64.png',
	},
	{
		name: 'Makedonija',
		callingNumber: '+389',
		code: 'MK',
		flag: 'https://flagsapi.com/MK/flat/64.png',
	},
	{
		name: 'Madagaskar',
		callingNumber: '+261',
		code: 'MG',
		flag: 'https://flagsapi.com/MG/flat/64.png',
	},
	{
		name: 'Malavi',
		callingNumber: '+265',
		code: 'MW',
		flag: 'https://flagsapi.com/MW/flat/64.png',
	},
	{
		name: 'Malezija',
		callingNumber: '+60',
		code: 'MY',
		flag: 'https://flagsapi.com/MY/flat/64.png',
	},
	{
		name: 'Maldivi',
		callingNumber: '+960',
		code: 'MV',
		flag: 'https://flagsapi.com/MV/flat/64.png',
	},
	{
		name: 'Mali',
		callingNumber: '+223',
		code: 'ML',
		flag: 'https://flagsapi.com/ML/flat/64.png',
	},
	{
		name: 'Malta',
		callingNumber: '+356',
		code: 'MT',
		flag: 'https://flagsapi.com/MT/flat/64.png',
	},
	{
		name: 'Maroko',
		callingNumber: '+212',
		code: 'MA',
		flag: 'https://flagsapi.com/MA/flat/64.png',
	},
	{
		name: 'Mauritanija',
		callingNumber: '+222',
		code: 'MR',
		flag: 'https://flagsapi.com/MR/flat/64.png',
	},
	{
		name: 'Mauricijus',
		callingNumber: '+230',
		code: 'MU',
		flag: 'https://flagsapi.com/MU/flat/64.png',
	},
	{
		name: 'Meksiko',
		callingNumber: '+52',
		code: 'MX',
		flag: 'https://flagsapi.com/MX/flat/64.png',
	},
	{
		name: 'Moldavija',
		callingNumber: '+373',
		code: 'MD',
		flag: 'https://flagsapi.com/MD/flat/64.png',
	},
	{
		name: 'Monako',
		callingNumber: '+377',
		code: 'MC',
		flag: 'https://flagsapi.com/MC/flat/64.png',
	},
	{
		name: 'Mongolija',
		callingNumber: '+976',
		code: 'MN',
		flag: 'https://flagsapi.com/MN/flat/64.png',
	},
	{
		name: 'Crna Gora',
		callingNumber: '+382',
		code: 'ME',
		flag: 'https://flagsapi.com/ME/flat/64.png',
	},
	{
		name: 'Maršalovi Ostrva',
		callingNumber: '+692',
		code: 'MH',
		flag: 'https://flagsapi.com/MH/flat/64.png',
	},
	{
		name: 'Mozambik',
		callingNumber: '+258',
		code: 'MZ',
		flag: 'https://flagsapi.com/MZ/flat/64.png',
	},
	{
		name: 'Mjanmar (Burma)',
		callingNumber: '+95',
		code: 'MM',
		flag: 'https://flagsapi.com/MM/flat/64.png',
	},
	{
		name: 'Namibija',
		callingNumber: '+264',
		code: 'NA',
		flag: 'https://flagsapi.com/NA/flat/64.png',
	},
	{
		name: 'Nauru',
		callingNumber: '+674',
		code: 'NR',
		flag: 'https://flagsapi.com/NR/flat/64.png',
	},
	{
		name: 'Nepal',
		callingNumber: '+977',
		code: 'NP',
		flag: 'https://flagsapi.com/NP/flat/64.png',
	},
	{
		name: 'Holandija',
		callingNumber: '+31',
		code: 'NL',
		flag: 'https://flagsapi.com/NL/flat/64.png',
	},
	{
		name: 'Nova Kaledonija',
		callingNumber: '+687',
		code: 'NC',
		flag: 'https://flagsapi.com/NC/flat/64.png',
	},
	{
		name: 'Novi Zeland',
		callingNumber: '+64',
		code: 'NZ',
		flag: 'https://flagsapi.com/NZ/flat/64.png',
	},
	{
		name: 'Nicaragua',
		callingNumber: '+505',
		code: 'NI',
		flag: 'https://flagsapi.com/NI/flat/64.png',
	},
	{
		name: 'Niger',
		callingNumber: '+227',
		code: 'NE',
		flag: 'https://flagsapi.com/NE/flat/64.png',
	},
	{
		name: 'Nigerija',
		callingNumber: '+234',
		code: 'NG',
		flag: 'https://flagsapi.com/NG/flat/64.png',
	},
	{
		name: 'Severna Koreja',
		callingNumber: '+850',
		code: 'KP',
		flag: 'https://flagsapi.com/KP/flat/64.png',
	},
	{
		name: 'Norveška',
		callingNumber: '+47',
		code: 'NO',
		flag: 'https://flagsapi.com/NO/flat/64.png',
	},
	{
		name: 'Oman',
		callingNumber: '+968',
		code: 'OM',
		flag: 'https://flagsapi.com/OM/flat/64.png',
	},
	{
		name: 'Pakistan',
		callingNumber: '+92',
		code: 'PK',
		flag: 'https://flagsapi.com/PK/flat/64.png',
	},
	{
		name: 'Palau',
		callingNumber: '+680',
		code: 'PW',
		flag: 'https://flagsapi.com/PW/flat/64.png',
	},
	{
		name: 'Panama',
		callingNumber: '+507',
		code: 'PA',
		flag: 'https://flagsapi.com/PA/flat/64.png',
	},
	{
		name: 'Papua Nova Gvineja',
		callingNumber: '+675',
		code: 'PG',
		flag: 'https://flagsapi.com/PG/flat/64.png',
	},
	{
		name: 'Paragvaj',
		callingNumber: '+595',
		code: 'PY',
		flag: 'https://flagsapi.com/PY/flat/64.png',
	},
	{
		name: 'Peru',
		callingNumber: '+51',
		code: 'PE',
		flag: 'https://flagsapi.com/PE/flat/64.png',
	},
	{
		name: 'Filipini',
		callingNumber: '+63',
		code: 'PH',
		flag: 'https://flagsapi.com/PH/flat/64.png',
	},
	{
		name: 'Poljska',
		callingNumber: '+48',
		code: 'PL',
		flag: 'https://flagsapi.com/PL/flat/64.png',
	},
	{
		name: 'Portugalija',
		callingNumber: '+351',
		code: 'PT',
		flag: 'https://flagsapi.com/PT/flat/64.png',
	},
	{
		name: 'Katar',
		callingNumber: '+974',
		code: 'QA',
		flag: 'https://flagsapi.com/QA/flat/64.png',
	},
	{
		name: 'Rumunija',
		callingNumber: '+40',
		code: 'RO',
		flag: 'https://flagsapi.com/RO/flat/64.png',
	},
	{
		name: 'Rusija',
		callingNumber: '+7',
		code: 'RU',
		flag: 'https://flagsapi.com/RU/flat/64.png',
	},
	{
		name: 'Ruanda',
		callingNumber: '+250',
		code: 'RW',
		flag: 'https://flagsapi.com/RW/flat/64.png',
	},
	{
		name: 'Sveti Kits i Nevis',
		callingNumber: '+1869',
		code: 'KN',
		flag: 'https://flagsapi.com/KN/flat/64.png',
	},
	{
		name: 'Sveti Lucija',
		callingNumber: '+1758',
		code: 'LC',
		flag: 'https://flagsapi.com/LC/flat/64.png',
	},
	{
		name: 'Sveti Vinsent i Grenadini',
		callingNumber: '+1784',
		code: 'VC',
		flag: 'https://flagsapi.com/VC/flat/64.png',
	},
	{
		name: 'Samoa',
		callingNumber: '+685',
		code: 'WS',
		flag: 'https://flagsapi.com/WS/flat/64.png',
	},
	{
		name: 'San Marino',
		callingNumber: '+378',
		code: 'SM',
		flag: 'https://flagsapi.com/SM/flat/64.png',
	},
	{
		name: 'Saudijska Arabija',
		callingNumber: '+966',
		code: 'SA',
		flag: 'https://flagsapi.com/SA/flat/64.png',
	},
	{
		name: 'Senegal',
		callingNumber: '+221',
		code: 'SN',
		flag: 'https://flagsapi.com/SN/flat/64.png',
	},
	{
		name: 'Sejšeli',
		callingNumber: '+248',
		code: 'SC',
		flag: 'https://flagsapi.com/SC/flat/64.png',
	},
	{
		name: 'Sijera Leone',
		callingNumber: '+232',
		code: 'SL',
		flag: 'https://flagsapi.com/SL/flat/64.png',
	},
	{
		name: 'Singapur',
		callingNumber: '+65',
		code: 'SG',
		flag: 'https://flagsapi.com/SG/flat/64.png',
	},
	{
		name: 'Slovačka',
		callingNumber: '+421',
		code: 'SK',
		flag: 'https://flagsapi.com/SK/flat/64.png',
	},
	{
		name: 'Slovenija',
		callingNumber: '+386',
		code: 'SI',
		flag: 'https://flagsapi.com/SI/flat/64.png',
	},
	{
		name: 'Solomonska Ostrva',
		callingNumber: '+677',
		code: 'SB',
		flag: 'https://flagsapi.com/SB/flat/64.png',
	},
	{
		name: 'Somalija',
		callingNumber: '+252',
		code: 'SO',
		flag: 'https://flagsapi.com/SO/flat/64.png',
	},
	{
		name: 'Južna Koreja',
		callingNumber: '+82',
		code: 'KR',
		flag: 'https://flagsapi.com/KR/flat/64.png',
	},
	{
		name: 'Južni Sudan',
		callingNumber: '+211',
		code: 'SS',
		flag: 'https://flagsapi.com/SS/flat/64.png',
	},
	{
		name: 'Španija',
		callingNumber: '+34',
		code: 'ES',
		flag: 'https://flagsapi.com/ES/flat/64.png',
	},
	{
		name: 'Sri Lanka',
		callingNumber: '+94',
		code: 'LK',
		flag: 'https://flagsapi.com/LK/flat/64.png',
	},
	{
		name: 'Sudan',
		callingNumber: '+249',
		code: 'SD',
		flag: 'https://flagsapi.com/SD/flat/64.png',
	},
	{
		name: 'Surinam',
		callingNumber: '+597',
		code: 'SR',
		flag: 'https://flagsapi.com/SR/flat/64.png',
	},
	{
		name: 'Švedska',
		callingNumber: '+46',
		code: 'SE',
		flag: 'https://flagsapi.com/SE/flat/64.png',
	},
	{
		name: 'Švajcarska',
		callingNumber: '+41',
		code: 'CH',
		flag: 'https://flagsapi.com/CH/flat/64.png',
	},
	{
		name: 'Sirija',
		callingNumber: '+963',
		code: 'SY',
		flag: 'https://flagsapi.com/SY/flat/64.png',
	},
	{
		name: 'Tadžikistan',
		callingNumber: '+992',
		code: 'TJ',
		flag: 'https://flagsapi.com/TJ/flat/64.png',
	},
	{
		name: 'Tanzanija',
		callingNumber: '+255',
		code: 'TZ',
		flag: 'https://flagsapi.com/TZ/flat/64.png',
	},
	{
		name: 'Tajvan',
		callingNumber: '+886',
		code: 'TW',
		flag: 'https://flagsapi.com/TW/flat/64.png',
	},
	{
		name: 'Tajland',
		callingNumber: '+66',
		code: 'TH',
		flag: 'https://flagsapi.com/TH/flat/64.png',
	},
	{
		name: 'Togo',
		callingNumber: '+228',
		code: 'TG',
		flag: 'https://flagsapi.com/TG/flat/64.png',
	},
	{
		name: 'Tonga',
		callingNumber: '+676',
		code: 'TO',
		flag: 'https://flagsapi.com/TO/flat/64.png',
	},
	{
		name: 'Trinidad i Tobago',
		callingNumber: '+1868',
		code: 'TT',
		flag: 'https://flagsapi.com/TT/flat/64.png',
	},
	{
		name: 'Tunis',
		callingNumber: '+216',
		code: 'TN',
		flag: 'https://flagsapi.com/TN/flat/64.png',
	},
	{
		name: 'Turska',
		callingNumber: '+90',
		code: 'TR',
		flag: 'https://flagsapi.com/TR/flat/64.png',
	},
	{
		name: 'Turkmenistan',
		callingNumber: '+993',
		code: 'TM',
		flag: 'https://flagsapi.com/TM/flat/64.png',
	},
	{
		name: 'Tuvalu',
		callingNumber: '+688',
		code: 'TV',
		flag: 'https://flagsapi.com/TV/flat/64.png',
	},
	{
		name: 'Uganda',
		callingNumber: '+256',
		code: 'UG',
		flag: 'https://flagsapi.com/UG/flat/64.png',
	},
	{
		name: 'Ukrajina',
		callingNumber: '+380',
		code: 'UA',
		flag: 'https://flagsapi.com/UA/flat/64.png',
	},
	{
		name: 'Ujedinjeni Arapski Emirati',
		callingNumber: '+971',
		code: 'AE',
		flag: 'https://flagsapi.com/AE/flat/64.png',
	},
	{
		name: 'Ujedinjeno Kraljevstvo',
		callingNumber: '+44',
		code: 'GB',
		flag: 'https://flagsapi.com/GB/flat/64.png',
	},
	{
		name: 'Urugvaj',
		callingNumber: '+598',
		code: 'UY',
		flag: 'https://flagsapi.com/UY/flat/64.png',
	},
	{
		name: 'Uzbekistan',
		callingNumber: '+998',
		code: 'UZ',
		flag: 'https://flagsapi.com/UZ/flat/64.png',
	},
	{
		name: 'Vanuatu',
		callingNumber: '+678',
		code: 'VU',
		flag: 'https://flagsapi.com/VU/flat/64.png',
	},
	{
		name: 'Vatikan',
		callingNumber: '+379',
		code: 'VA',
		flag: 'https://flagsapi.com/VA/flat/64.png',
	},
	{
		name: 'Venecuela',
		callingNumber: '+58',
		code: 'VE',
		flag: 'https://flagsapi.com/VE/flat/64.png',
	},
	{
		name: 'Vijetnam',
		callingNumber: '+84',
		code: 'VN',
		flag: 'https://flagsapi.com/VN/flat/64.png',
	},
	{
		name: 'Jemen',
		callingNumber: '+967',
		code: 'YE',
		flag: 'https://flagsapi.com/YE/flat/64.png',
	},
	{
		name: 'Zambija',
		callingNumber: '+260',
		code: 'ZM',
		flag: 'https://flagsapi.com/ZM/flat/64.png',
	},
	{
		name: 'Zimbabve',
		callingNumber: '+263',
		code: 'ZW',
		flag: 'https://flagsapi.com/ZW/flat/64.png',
	},
];
